name: Slack alert for dev branch

on:
  push:
    branches:
      - main
      - test

  pull_request:
    branches:
      - main
  #github action에서 수동으로 돌릴 수 있음
  # workflow_dispatch:

name: Send TIL to test Slack API

on: [push]

jobs:
  deploy:
    name: Send TIL to Slack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy my app
        run: |
          bash test1.sh ${{ secrets.SLACK_WEBHOOK_URL }} ${{ secrets.AUTHOR_NAME }}