name: Slack alert for dev branch

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  #github action에서 수동으로 돌릴 수 있음
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          custom_payload: |
            {
              "key": "value",
              "foo": "bar"
            }
          status: ${{ job.status }}
          # author_name: test slack web hook
          # fields: repo,commit,message,author,action,eventName,ref,workflow,job,took
          # mention: here
          # if_mention: failure,cancelled
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "key": "value",
              "foo": "bar"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}