name: Deploy

on: [push]

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  deploy:
    name: Deploy my app

    runs-on: ubuntu-latest
    env:
      TEST_CHAR : "HELLo"
      # CURRENT_DATE : "$(date +%Y%m%d)"".md"

    steps:
      - uses: actions/checkout@v3
      - name: Deploy my app
        run: |
          echo $TEST_CHAR | bash test1.sh ${{ env.SLACK_WEBHOOK_URL }}