name: Send TIL to test Slack API

on: [push]

jobs:
  send-slack:
    name: Send TIL to Slack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy my app
        run: |
          git diff --name-only HEAD^ HEAD
          bash sendSlack.sh ${{ secrets.SLACK_WEBHOOK_URL }} ${{ secrets.AUTHOR_NAME }}
